// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgajzoyytijxqpcvzhxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYWp6b3l5dGlqeHFwY3Z6aHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDgzNzMsImV4cCI6MjA3MDcyNDM3M30.Ja6ghgqVpeDwITZAAo4ge2gvua1xFNSZ0JxVDolhyFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});